require('dotenv').config();
const express = require('express');
const app = express();
const port = process.env.PORT || 4000;
app.use(express.json());
app.use('/api/auth', require('./routes/auth'));
app.use('/api/users', require('./routes/users'));
app.use('/api/wallet', require('./routes/wallet'));
app.use('/api/ranking', require('./routes/ranking'));
app.use('/api/submissions', require('./routes/submissions'));
app.use('/api/redeem', require('./routes/redeem'));
app.get('/health', (req, res) => res.json({ ok: true }));
app.listen(port, () => { console.log('Server listening on port', port); });
